services:
  - type: web
    name: peanut-reading-api
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        fromService:
          type: web
          name: peanut-reading-web
          property: url
      # Supabase
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      # Google AI
      - key: GOOGLE_AI_API_KEY
        sync: false
      - key: GOOGLE_CLOUD_PROJECT_ID
        sync: false
      # Google Cloud Service Account (as environment variables)
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
      # OpenAI
      - key: OPENAI_API_KEY
        sync: false
      # Security
      - key: JWT_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      # Rate Limiting
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      # File Upload
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: ALLOWED_AUDIO_FORMATS
        value: audio/wav,audio/mp3,audio/m4a,audio/webm